apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-gateway-cm
data:
  CONFIG_SERVER_INSTANCE_HOSTNAME: "http://config-server-svc"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-cm
data:
  hostname: "mysql-svc"